# Generated by Django 3.1.7 on 2021-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='id',
        ),
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(blank=True, max_length=45, primary_key=True, serialize=False),
        ),
    ]
