# Generated by Django 3.1.7 on 2021-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('user_category', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, db_column='District', null=True)),
            ],
            options={
                'db_table': 'mobile_user',
                'managed': False,
            },
        ),
    ]
