# Generated by Django 3.2.4 on 2021-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mobileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('domain', models.TextField(blank=True, null=True)),
                ('caseid', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('date_ref', models.TextField(blank=True, null=True)),
                ('statut', models.TextField(blank=True, null=True)),
                ('indices_femme', models.TextField(blank=True, db_column='indices.femme', null=True)),
                ('closed', models.BooleanField(blank=True, null=True)),
                ('last_modified_by_user_username', models.TextField(blank=True, null=True)),
                ('opened_date', models.DateTimeField(blank=True, null=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('case_link', models.TextField(blank=True, null=True)),
                ('conseil_ipc', models.TextField(blank=True, null=True)),
                ('consulte_ref', models.TextField(blank=True, null=True)),
                ('date_vis_ref', models.TextField(blank=True, null=True)),
                ('retours_sur_la_visite', models.TextField(blank=True, null=True)),
                ('type_de_conseils', models.TextField(blank=True, null=True)),
                ('type_ref', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reference',
                'managed': False,
            },
        ),
    ]
